name: CI

on:
    push:
        branches:
            - main
    pull_request:
        types: [ opened, synchronize, reopened, ready_for_review ]

jobs:
    test:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                node-version: [ 10.x, 12.x, 14.x ]

        steps:
            -   uses: actions/checkout@v2

            -   name: Use Node.js ${{ matrix.node-version }}
                uses: actions/setup-node@v2
                with:
                    node-version: ${{ matrix.node-version }}

            -   run: yarn install --frozen-lockfile

            -   run: yarn test

    lint:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2

            -   run: yarn install --frozen-lockfile

            -   run: yarn lint
