name: CI

on:
    push:
        branches:
            - main
    pull_request:
        types: [opened, synchronize, reopened, ready_for_review]

jobs:
    test:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                node-version: [14.x, 16.x, 18.x, 20.x]

        steps:
            -   uses: actions/checkout@v2
                with:
                    fetch-depth: '100'

            -   name: Use Node.js ${{ matrix.node-version }}
                uses: actions/setup-node@v2
                with:
                    node-version: ${{ matrix.node-version }}

            -   name: 'Rush: Checking for missing change logs...'
                run: node common/scripts/install-run-rush.js change -v

            -   name: 'Rush: Installing...'
                run: node common/scripts/install-run-rush.js install

            -   name: 'Rush: Building...'
                run: node common/scripts/install-run-rush.js rebuild --verbose

            -   name: 'Rush: Testing...'
                run: node common/scripts/install-run-rush.js test --verbose

    lint:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
                with:
                    fetch-depth: '100'

            -   name: 'Rush: Installing...'
                run: node common/scripts/install-run-rush.js install

            -   name: 'Rush: Building...'
                run: node common/scripts/install-run-rush.js rebuild --verbose

            -   name: 'Rush: Linting...'
                run: node common/scripts/install-run-rush.js lint --verbose
