name: Release

on:
    push:
        branches:
            - main

env:
    CI: true

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2

            -   name: Install Node.js
                uses: actions/setup-node@v2

            -   run: yarn install --frozen-lockfile

            -   run: yarn build

            -   run: yarn semantic-release
                env:
                    NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
