name: Release

on:
    push:
        branches:
            - main

env:
    CI: true

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
                with:
                    fetch-depth: '100'

            -   run: 'git config --local user.email hugo@alliau.me'
            -   run: 'git config --local user.name Hugo Alliaume'

            -   name: 'Rush: Verify Change Logs...'
                run: node common/scripts/install-run-rush.js change --verify

            -   name: 'Rush: Installing...'
                run: node common/scripts/install-run-rush.js install

            -   name: 'Rush: Building...'
                run: node common/scripts/install-run-rush.js rebuild --verbose

            -   name: 'Rush: Version...'
                run: node common/scripts/install-run-rush.js version --bump --version-policy eslint-config-generator --target-branch main

            -   name: 'Rush: Publish...'
                run: node common/scripts/install-run-rush.js publish --apply --publish --include-all --target-branch main --add-commit-details --set-access-level public
                env:
                    NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
